baseURL = "https://nicholas.wang/"
languageCode = "en-us"
title = "Nicholas Wang"
theme = "smol"

enableGitInfo = true

# Parameters
[params]
    subtitle = ""
    dateFmt = "Jan 02, 2006"

# Header
[menu]
  [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1

  [[menu.main]]
        identifier = "articles"
        name = "Articles"
        url = "/articles/"
        weight = 2

  [[menu.main]]
        identifier = "cv"
        name = "CV"
        url = "cv.pdf"
        weight = 6

  [[menu.main]]
        identifier = "gpg"
        name = "GPG Key"
        url = "/gpg"
        weight = 4

  [[menu.main]]
        identifier = "dn42"
        name = "DN42"
        url = "/dn42"
        weight = 5

# Footer
  [[menu.footer]]
        name = "GitHub"
        url = "https://github.com/nicholascw"
        weight = 1

    [[menu.footer]]
        name = "Telegram"
        url = "https://t.me/nicholascw"
        weight = 2

    [[menu.footer]]
        name = "E-mail"
        url = "mailto:me@nicho1as.wang"
        weight = 3

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
