baseURL = "https://nicholas.wang/"
languageCode = "en-us"
title = "Chenkai (Nicholas) Wang"
theme = "smol"

enableGitInfo = true

# Parameters
[params]
    subtitle = ""
    dateFmt = "Jan 02, 2006"

# Header
[menu]
  [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1

  [[menu.main]]
        identifier = "articles"
        name = "Articles"
        url = "/articles/"
        weight = 2

  [[menu.main]]
        identifier = "pgp"
        name = "PGP Key"
        url = "/pgp"
        weight = 4

#  [[menu.main]]
#        identifier = "dn42"
#        name = "DN42"
#        url = "/dn42"
#        weight = 5

  [[menu.main]]
        identifier = "cv"
        name = "CV"
        url = "cv.pdf"
        weight = 6


# Footer
  [[menu.footer]]
        name = "GitHub"
        url = "https://github.com/nicholascw"
        weight = 1

#  [[menu.footer]]
#        name = "Telegram"
#        url = "https://t.me/nicholascw"
#        weight = 2

  [[menu.footer]]
        name = "Matrix"
        url = "https://matrix.to/#/@nicholascw:matrix.org"
        weight = 2


  [[menu.footer]]
        name = "E-mail"
        url = "mailto:i@nw.ci"
        weight = 3

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
